name: Setup

description: Sets up the whole monorepo and install dependencies

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Set up Git user
      shell: bash
      run: |
        git config --global user.name "Chad.K"
        git config --global user.email "kangqod@naver.com"

    - name: Install dependencies with custom settings
      shell: bash
      run: pnpm install --verbose
