name: Quality
permissions:
  contents: read

on:
  pull_request:
    branches:
      - 'master'

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests
        run: pnpm test

  lint:
    name: Biome lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run lint
        run: pnpm lint
        continue-on-error: true

  format:
    name: Biome format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run format
        run: pnpm format
